### ISSUE TITLE
Little tiny style issues

### ISSUE THREAD

**Issue by tonytang-microsoft-com** [Azure/autorest#229]
```C#
in data model
        /// <summary>
        /// Gets or sets the state. Possible values for this property include:
        /// 'NotSpecified', 'Enabled', 'Disabled', 'Deleted', 'Suspended' (missing full stop)
        /// </summary>
        [JsonProperty(PropertyName = "properties.state")]
        public WorkflowState? State { get; set; }
```

```C#
in client
        /// <summary>
        /// Management credentials for Azure.  (should begin with 'The')
        /// </summary>
        ServiceClientCredentials Credentials { get; }
```

```C#
in operation extensions
            /// <summary>
            /// Gets a list of workflow runs.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='nextPageLink'>
            /// NextLink from the previous successful call to List operation. (should begin with 'The')
            /// </param>
            /// <param name='cancellationToken'>
            /// Cancellation token. (should begin with 'The')
            /// </param>
            public static async Task<Page<WorkflowRun>> ListNextAsync( this IWorkflowRunsOperations operations, string nextPageLink, CancellationToken cancellationToken = default(CancellationToken))
            {
                AzureOperationResponse<Page<WorkflowRun>> result = await operations.ListNextWithHttpMessagesAsync(nextPageLink, null, cancellationToken).ConfigureAwait(false);
                return result.Body;
            }
```

```C#
in data model. where can we put description in swagger? I tried adding description for definition, but looks like no effect.
    /// <summary> (empty summary)
    /// </summary>
    public partial class WorkflowAccessKey : SubResource
```

```C#
in operations
    /// <summary> (empty summary)
    /// </summary>
    public partial interface IWorkflowAccessKeysOperations
```

**Comment by hovsepm** [comment]
Fixed in dev branch.

**Comment by devigned** [comment]
@hovsepm is there a test that is passing that verifies this fix?

**Comment by markcowl** [comment]
@tonytang-microsoft-com  which issue is still reproing for you?

**Comment by hovsepm** [comment]
Fixed in dev branch.
