### ISSUE TITLE
Autorest fails if ancestor has no properties (and it shouldn't)

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#2671]
Let's say something like this:
```json
    "Article": {
      "allOf": [
        {
          "$ref": "#/definitions/CreativeWork"
        }
      ],
      "type": "object"
    },
    "NewsArticle": {
      "description": "Defines a news article.",
      "allOf": [
        {
          "$ref": "#/definitions/Article"
        }
      ],
      "type": "object",
      "properties": {}
    },
```

Autorest fails:
```shell
AutoRest code generation utility [version: 2.0.4166]

(C) 2017 Microsoft Corporation.
https://aka.ms/autorest
Loading AutoRest extension '@microsoft.azure/autorest.python' (preview)
Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.22)
FATAL: The schema's 'NewsArticle' ancestors should have at lease one property
FATAL: AutoRest.Core.Logging.CodeGenerationException: The schema's 'NewsArticle' ancestors should have at lease one property
   at AutoRest.Modeler.SwaggerModeler.BuildCompositeTypes() in C:\Users\ci\AppData\Local\Temp\PUBLISHv6236\20_20171009T223650\autorest.modeler\src\SwaggerModeler.cs:line 312
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in C:\Users\ci\AppData\Local\Temp\PUBLISHv6236\20_20171009T223650\autorest.modeler\src\SwaggerModeler.cs:line 69
   at AutoRest.Modeler.Program.<ProcessInternal>d2.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHv6236\20_20171009T223650\autorest.modeler\src\Program.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d15.MoveNext()
```

Discussed with @amarzavery and looked at the Swagger spec, there is nothing that prevents an ancestor to do not have properties (whether it's a good Swagger or not is not the question here, this respects the spec).

Impact [WebSearch](https://github.com/Azure/azure-rest-api-specs/blob/58ff8cc164c555accbbea0066783d9608a1594e0/specification/cognitiveservices/data-plane/WebSearch/v1.0/WebSearch.json).

FYI @stefanvalianu

**Comment by olydis** [comment]
yup that's on my radar and if I'm not mistaken I even have a branch sitting somewhere that has a fix - the spec will be the perfect testcase 😉

**Comment by olydis** [comment]
Sweet, there even was [this](https://github.com/Azure/autorest.modeler/pull/21) PR - tested against websearch, worked out of the box (at least in C#). Note that by default we don't even generate empty classes, ancestor or not (reason? I don't know!) - I introduced `--generate-empty-classes` flag for that, which now *also* disables the empty ancestor error. I'd totally be in favor of supporting empty classes by default, but wanted to have some good test cases before that. I tend to assume that at least some old decisions made in AutoRest make sense, especially if so much effort was put into ensuring it!?

To test this in Python, you gotta add `--generate-empty-classes --use=@microsoft.azure/autorest.modeler@preview`

**Comment by olydis** [comment]
fixed by https://github.com/Azure/autorest.modeler/pull/21

**Comment by epet** [comment]
I'm still seeing this issue, am I missing something on my command?
F:\some_service_file>autorest --generate-empty-classes --use=@microsoft.azure/autorest.modeler@preview --input-file="F:\some_service_file\some_service_file.json" --namespace="some.service.namespace" --csharp --csharp.output-folder="F:\some_service_file\csharpcodegen\csharp" --java --java.output-folder="F:\some_service_file\javacodegen\java" --nodejs --nodejs.output-folder="F:\some_service_file\nodejscodegen\nodejs" --python --python.output-folder="F:\some_service_file\pythoncodegen\python" --go --go.output-folder="F:\some_service_file\gocodegen\go" --ruby --ruby.output-folder="F:\some_service_file\rubycodegen\ruby"
AutoRest code generation utility [version: 2.0.4283; node: v8.11.2]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\autorest-core -> C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\app.js
C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\autorest-language-service -> C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\language-service\language-service.js
   Loading AutoRest core      'C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4283)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (preview->2.3.55)
   Installing AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79)
   Loading AutoRest extension '@microsoft.azure/autorest.go' (~2.1.47->2.1.61)
   Loading AutoRest extension '@microsoft.azure/autorest.java' (~2.1.32->2.1.32)
   Loading AutoRest extension '@microsoft.azure/autorest.nodejs' (~2.1.25->2.1.25)
   Loading AutoRest extension '@microsoft.azure/autorest.python' (~2.1.26->2.1.26)
   Loading AutoRest extension '@microsoft.azure/autorest.ruby' (~3.1.26->3.1.26)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.22->2.1.22)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38->2.3.38)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
FATAL: The schema's 'Operation' ancestors should have at lease one property
FATAL: AutoRest.Core.Logging.CodeGenerationException: The schema's 'Operation' ancestors should have at lease one property
   at AutoRest.Modeler.SwaggerModeler.BuildCompositeTypes() in C:\Users\ci\AppData\Local\Temp\PUBLISHv6236\20_20171009T223650\autorest.modeler\src\SwaggerModeler.cs:line 312
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in C:\Users\ci\AppData\Local\Temp\PUBLISHv6236\20_20171009T223650\autorest.modeler\src\SwaggerModeler.cs:line 69
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHv6236\20_20171009T223650\autorest.modeler\src\Program.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: ruby/modeler - FAILED
FATAL: Error: Plugin modeler reported failure.
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin modeler reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 29)
(node:26296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin modeler reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin modeler reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 31)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin modeler reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 32)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin modeler reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 33)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin modeler reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 34)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin modeler reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 35)
FATAL: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoRest.Modeler.OperationBuilder.<>cDisplayClass13_0.<BuildMethodReturnType>b0(Stack`1 typeStack) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 376
   at System.Collections.Generic.List1.ForEach(Action1 action)
   at AutoRest.Modeler.OperationBuilder.BuildMethodReturnType(List`1 types, IModelType headerType) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 369
   at AutoRest.Modeler.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 197
   at AutoRest.Modeler.SwaggerModeler.BuildMethod(HttpMethod httpMethod, String url, String name, Operation operation) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 404
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 106
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoRest.Modeler.OperationBuilder.<>cDisplayClass13_0.<BuildMethodReturnType>b0(Stack`1 typeStack) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 376
   at System.Collections.Generic.List1.ForEach(Action1 action)
   at AutoRest.Modeler.OperationBuilder.BuildMethodReturnType(List`1 types, IModelType headerType) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 369
   at AutoRest.Modeler.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 197
   at AutoRest.Modeler.SwaggerModeler.BuildMethod(HttpMethod httpMethod, String url, String name, Operation operation) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 404
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 106
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoRest.Modeler.OperationBuilder.<>cDisplayClass13_0.<BuildMethodReturnType>b0(Stack`1 typeStack) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 376
   at System.Collections.Generic.List1.ForEach(Action1 action)
   at AutoRest.Modeler.OperationBuilder.BuildMethodReturnType(List`1 types, IModelType headerType) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 369
   at AutoRest.Modeler.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 197
   at AutoRest.Modeler.SwaggerModeler.BuildMethod(HttpMethod httpMethod, String url, String name, Operation operation) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 404
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 106
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoRest.Modeler.OperationBuilder.<>cDisplayClass13_0.<BuildMethodReturnType>b0(Stack`1 typeStack) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 376
   at System.Collections.Generic.List1.ForEach(Action1 action)
   at AutoRest.Modeler.OperationBuilder.BuildMethodReturnType(List`1 types, IModelType headerType) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 369
   at AutoRest.Modeler.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 197
   at AutoRest.Modeler.SwaggerModeler.BuildMethod(HttpMethod httpMethod, String url, String name, Operation operation) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 404
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 106
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoRest.Modeler.OperationBuilder.<>cDisplayClass13_0.<BuildMethodReturnType>b0(Stack`1 typeStack) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 376
   at System.Collections.Generic.List1.ForEach(Action1 action)
   at AutoRest.Modeler.OperationBuilder.BuildMethodReturnType(List`1 types, IModelType headerType) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 369
   at AutoRest.Modeler.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 197
   at AutoRest.Modeler.SwaggerModeler.BuildMethod(HttpMethod httpMethod, String url, String name, Operation operation) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 404
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 106
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: python/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 36)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 37)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 38)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 39)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 40)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 41)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 42)
FATAL: java/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 43)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 44)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 45)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 46)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 47)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 48)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 49)
FATAL: csharp/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 50)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 51)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 52)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 53)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 54)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 55)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 56)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 57)
FATAL: go/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 58)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 59)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 60)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 61)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 62)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 63)
(node:26296) UnhandledPromiseRejectionWarning: Error: Plugin imodeler1 reported failure.
    at GetPlugin_External (C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:114:19)
    at <anonymous>
(node:26296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 64)
FATAL: nodejs/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
Process() cancelled due to exception : Plugin modeler reported failure.
  Error: Plugin modeler reported failure.

**Comment by fearthecowboy** [comment]
It might be useful to isolate which generator is causing the problem.

Different generators can use different versions of the modeler, and the one that uses an older modeler may not support empty base models:

``` text
Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.22->2.1.22)
Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38->2.3.38)
Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
```

Can you see which language is causing the problem?

**Comment by epet** [comment]
looks like they all failed. Am I missing something?
FATAL: ruby/modeler - FAILED
FATAL: python/imodeler1 - FAILED
FATAL: java/imodeler1 - FAILED
FATAL: csharp/imodeler1 - FAILED
FATAL: go/imodeler1 - FAILED
FATAL: nodejs/imodeler1 - FAILED

**Comment by fearthecowboy** [comment]
One failure might make them all fail. 

Regardless, I'm not sure that the original bug's problem is the problem that you're seeing. I think there is something else wrong. 

Can you open a new bug and post the swagger file?

**Comment by farhadnowzari** [comment]
So the AutoRest with VisualStudio AddRestApi still doesn't work.
So the workaround until microsoft uses --generate-empty-classes would be to simply add a unused property inside that class.
public int? Fake { get; set; }
then create the client and then remove it from your project.
The reason that we could not use AutoRest cli is that on one of the development machines the installation is corrupted.
So we did this and the GUI works.
