### ISSUE TITLE
Autorest python sdk generation failing: Cannot resolve pipeline stage 'openapi-document/identity'

### ISSUE THREAD

**Issue by DheerendraRathor** [Azure/autorest#2737]
~\specification\recoveryservicesbackup\resource-manager [violations +1 ~3 -0 !]> autorest --python --verbose --debug
AutoRest code generation utility [version: 2.0.4166]

(C) 2017 Microsoft Corporation.
https://aka.ms/autorest
[11:13:50] Network Enabled: true
[11:13:50] The most recent installed version is 2.0.4168
[11:13:50] requesting current version '2.0.4168'
[11:13:50] Starting @microsoft.azure/autorest-core from C:\Users\xxxx\.autorest\@microsoft.azure_autorest-core@2.0.4168
[11:13:50] Using core from: 'C:\Users\xxxx\.autorest\@microsoft.azure_autorest-core@2.0.4168\node_modules\@microsoft.azure\autorest-core'
DEBUG: Creating ConfigurationView : 3 sections.
DEBUG: Creating ConfigurationView : 9 sections.
DEBUG: Creating ConfigurationView : 9 sections.
DEBUG: Creating ConfigurationView : 34 sections.
Loading AutoRest extension '@microsoft.azure/autorest.python' (~2.0.0)
DEBUG: Creating ConfigurationView : 36 sections.
Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38)
DEBUG: Creating ConfigurationView : 39 sections.
DEBUG: Creating ConfigurationView : 39 sections.
DEBUG: Creating ConfigurationView : 2 sections.
DEBUG: Creating ConfigurationView : 2 sections.
DEBUG: Creating ConfigurationView : 2 sections.
Process() Cancelled due to exception : Cannot resolve pipeline stage 'openapi-document/identity'.
```js
Error: Cannot resolve pipeline stage 'openapi-document/identity'.
    at resolvePipelineStageName (C:\Users\xxxx\.autorest\@microsoft.azure_autorest-core@2.0.4168\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:142: 15)
    at inputs.map (C:\Users\xxxx\.autorest\@microsoft.azure_autorest-core@2.0.4168\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:159: 108)
    at Array.map (<anonymous>)
    at createNodesAndSuffixes (C:\Users\xxxx\.autorest\@microsoft.azure_autorest-core@2.0.4168\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:159: 97)
    at BuildPipeline (C:\Users\xxxx\.autorest\@microsoft.azure_autorest-core@2.0.4168\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:205: 9)
    at Object.RunPipeline (C:\Users\xxxx\.autorest\@microsoft.azure_autorest-core@2.0.4168\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:261: 22)
    at <anonymous>
```

**Comment by DheerendraRathor** [comment]
Adding more info:
It is working fine for C#.
```
Installing AutoRest extension '@microsoft.azure/autorest.csharp' (~2.1.0)
Installing AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.22)
```

AutoRest code generation utility [version: 2.0.4166]

(C) 2017 Microsoft Corporation.
https://aka.ms/autorest
Showing All Installed Extensions
```
 Type       Extension Name                     Version   location
 core       @microsoft.azure/autorest-core     2.0.4168  C:\Users\xxxx\.autorest\@microsoft.azure_autorest-core@2.0.4168
 extension  @microsoft.azure/autorest.csharp   2.1.28    C:\Users\xxxx\.autorest\@microsoft.azure_autorest.csharp@2.1.28
 extension  @microsoft.azure/autorest.modeler  2.1.22    C:\Users\xxxx\.autorest\@microsoft.azure_autorest.modeler@2.1.22
 extension  @microsoft.azure/autorest.modeler  2.3.38    C:\Users\xxxx\.autorest\@microsoft.azure_autorest.modeler@2.3.38
 extension  @microsoft.azure/autorest.python   2.0.25    C:\Users\xxxx\.autorest\@microsoft.azure_autorest.python@2.0.25
```

**Comment by fearthecowboy** [comment]
Python (well, the modeler that it uses) apparently requires the preview AutoRest.

upgrade to the preview:

``` powershell 
npm install -g autorest@preview
autorest --reset
```

**Comment by lmazuel** [comment]
Preview is now stable, using latest issue should be fixed.

**Comment by DheerendraRathor** [comment]
Working with latest AutoRest now 😃 Closing this.

**Comment by priyankajayaswal1** [comment]
Hey, I am facing this and the solution doesn't resolve my issue. Would appreciate it if someone may help me with this.
```
autorest --v3 --input-file=swagger.json client_config.md
AutoRest code generation utility [cli version: 3.0.6187; node: v12.3.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\prjayasw\.autorest\@autorest_core@3.0.6306\node_modules\@autorest\core\dist' (3.0.6306)
   Installing AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79)
   Installed AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.84)
   Installing AutoRest extension '@autorest/python' (latest)
   Installed AutoRest extension '@autorest/python' (latest->5.1.0-preview.7)
   Installing AutoRest extension '@autorest/modelerfour' (4.15.400)
   Installed AutoRest extension '@autorest/modelerfour' (4.15.400->4.15.400)
   Installing AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55)
   Installed AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
  Error: Cannot resolve pipeline stage 'openapi-document/identity'.

```

I am creating chsarp and python both clients

**Comment by priyankajayaswal1** [comment]
@fearthecowboy wanted to check what may cause this.
