### ISSUE TITLE
C# Generation doesn't produce correct return type

### ISSUE THREAD

**Issue by ruant** [Azure/autorest#2870]
```
PS C:\WINDOWS\system32> autorest --info
AutoRest code generation utility [version: 2.0.4245; node: v7.10.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location
 core       @microsoft.azure/autorest-core           2.0.4245     C:\Users\Rune\AppData\Local\Temp\.autorest\@microsoft.azure_autorest-core@2.0.4245
 extension  @microsoft.azure/autorest.csharp         2.2.57       C:\Users\Rune\AppData\Local\Temp\.autorest\@microsoft.azure_autorest.csharp@2.2.57
 extension  @microsoft.azure/autorest.modeler        2.3.43       C:\Users\Rune\AppData\Local\Temp\.autorest\@microsoft.azure_autorest.modeler@2.3.43
```

API method code:
```
/// <summary>
/// Get all "Employee" items that has an Id starting with the given <paramref name="matchId"/>
/// </summary>
/// <param name="matchId">Partial Id to get all macthing items for</param>
/// <response code="200">Success</response>
/// <response code="400">BadRequest or underlying services has failed, check error message</response>
/// <response code="404">No items found</response>
[HttpGet("getEmployeesMatchingId/{matchId}")]
[ProducesResponseType(typeof(IEnumerable<string>), 200)]
[ProducesResponseType(typeof(string), 400)]
[ProducesResponseType(typeof(string), 404)]
public IActionResult GetAllMatchingIdStart(string matchId)
{
    var (status, message, data) = _employee.GetAllMatchingIdStart(matchId);
    switch (status)
    {
        case 200:
            return new OkObjectResult(data);
        case 404:
            return new NotFoundObjectResult(JsonConvert.SerializeObject(message));
        default:
            return new BadRequestObjectResult(JsonConvert.SerializeObject(message));
    }
}
```

Spec file generated:
```
"/api/employee/getEmployeesMatchingId/{matchId}": {
  "get": {
    "tags": [ "Employee" ],
    "summary": "Get all \"Employee\" items that has an Id starting with the given matchId",
    "operationId": "ApiEmployeeGetEmployeesMatchingIdByMatchIdGet",
    "consumes": [],
    "produces": [ "text/plain", "application/json", "text/json" ],
    "parameters": [
      {
        "name": "matchId",
        "in": "path",
        "description": "Partial Id to get all macthing items for",
        "required": true,
        "type": "string"
      }
    ],
    "responses": {
      "200": {
        "description": "Success",
        "schema": {
          "type": "array",
          "items": { "type": "string" }
        }
      },
      "400": {
        "description": "BadRequest or underlying services has failed, check error message",
        "schema": { "type": "string" }
      },
      "404": {
        "description": "No items found",
        "schema": { "type": "string" }
      }
    }
  }
}
```

And it produces this in the Extension generated file:
```
/// <summary>
/// Get all "Employee" items that has an Id starting with the given matchId
/// </summary>
/// <param name='operations'>
/// The operations group for this extension method.
/// </param>
/// <param name='matchId'>
/// Partial Id to get all macthing items for
/// </param>
public static object ApiEmployeeGetEmployeesMatchingIdByMatchIdGet(this IRESTfulAPI operations, string matchId)
{
    return operations.ApiEmployeeGetEmployeesMatchingIdByMatchIdGetAsync(matchId).GetAwaiter().GetResult();
}
```

But if I dig further in to the actual code that does something it has:
```
// Deserialize Response
if ((int)_statusCode == 200)
{
    _responseContent = await _httpResponse.Content.ReadAsStringAsync().ConfigureAwait(false);
    try
    {
        _result.Body = SafeJsonConvert.DeserializeObject<IList<string>>(_responseContent, DeserializationSettings);
    }
    catch (JsonException ex)
    {
        _httpRequest.Dispose();
        if (_httpResponse != null)
        {
            _httpResponse.Dispose();
        }
        throw new SerializationException("Unable to deserialize the response.", _responseContent, ex);
    }
}
```
  
  
__Is this a bug or am I doing something wrong here?__
What I would expect is either a IEnumerable<string> or IList<string> (that it kinda started generating) be returned all the way out.

**Comment by fearthecowboy** [comment]
You have multiple responses. Currently, AutoRest tries to make them all return values, but the only common return type at that point, is `object`

If you have a `default` response, that will be used to throw exceptions from the API. So replace that section with:



``` json
 "responses": {
      "200": {
        "description": "Success",
        "schema": {
          "type": "array",
          "items": { "type": "string" }
        }
      },
      "default": {
        "description": "No items found or BadRequest or underlying services has failed, check error message",
        "schema": { "type": "string" }
      }
```

**Comment by fearthecowboy** [comment]
FWIW -- We have support for error responses coming soon.

**Comment by ruant** [comment]
@fearthecowboy 
Makes sense when you spell it out for me like that :+1: 

Maybe a "fixed" response object would be a solution in the mean time, e.g.
```
public class EmployeeResponse {
  public bool Success { get; set; }
  public List<string> Result { get; set; }
  public string Error { get; set; }
}
```

I'll close this since it's in the making.  
Cheers!

**Comment by SkinnySackboy** [comment]
@fearthecowboy by any chance do you know when the error response support will be available, as we are currently seeing a very similar issue since upgrading to netcoreapp2.2 (where 404 responses are associated with a ProblemDetails response type, which causes autorest to generate <object> signatures as @ruant  described?

**Comment by kwskii** [comment]
Reporting on this same issue still 1 year later

**Comment by kehepo** [comment]
@kwskii you may have better luck with [NSwag](https://github.com/RicoSuter/NSwag)

**Comment by nallejacobsson** [comment]
Issue still exists. @fearthecowboy - any updates on this?

**Comment by fearthecowboy** [comment]
We're writing a new c# generator to fall in line with the way that the Azure Core work. The existing generator isn't getting any more attention. I imagine we're only a few weeks from having a preview of the new generator.

**Comment by kehepo** [comment]
Not sure why my reply earlier was deleted. I recommended giving [NSWag](https://github.com/RicoSuter/NSwag) a try before the issue gets addressed in Autorest.

**Comment by DavidNorena** [comment]
Would you apply the same changes to the autorest typescript as well ?

**Comment by SamuelDev** [comment]
I'm still seeing this in the v3 engine.  Was a solution ever reached?

**Comment by bzmo** [comment]
@fearthecowboy Any updates on the C# generator?

**Comment by poddubitskya** [comment]
Any news, guys?

**Comment by Tiberriver256** [comment]
Any update on this? Maybe we could re-open the issue until it's solved?

**Comment by n-rowe** [comment]
Has there been any update for this? A number of schemas I use have multiple response types and it's preventing me from automating generation since the schema needs to be manually resolved.
