### ISSUE TITLE
autorest@3.0.5139 and later hang on Linux due to bad shebang

### ISSUE THREAD

**Issue by kevinoid** [Azure/autorest#3198]
`autorest@3.0.5139` and later versions (including `3.0.5165`, the current `autorest@beta`) hang on direct invocation with any arguments.  Example:

```sh
cd "$(mktemp -d)"
npm init -y
npm install autorest@beta
./node_modules/.bin/autorest --help  # Consumes 100% CPU indefinitely, no output
```
This is due to the shebang line `#!/usr/bin/env node --max_old_space_size=16384` which was added in 2c9d5a5a3.  Since [Linux does not split arguments in shebangs](https://www.in-ulm.de/~mascheck/various/shebang/#splitting), this causes the following sequence:

1.  The kernel reads then parses the shebang and executes `/usr/bin/env "node --max_old_space_size=16384" ./node_modules/.bin/autorest`
2.  `env` sets an environment variable named `node --max_old_space_size` to `16384` then executes `./node_modules/.bin/autorest`.
3.  Goto 1

So the process becomes stuck in this loop indefinitely.

Thanks for considering,
Kevin

**Comment by fearthecowboy** [comment]
O_o. 

Hmm. @$%$*)%

That is a real damn pity.  I need that.

` node ./node_modules/.bin/autorest` works... um, I gotta go see if there's another way to smack that around.

**Comment by fearthecowboy** [comment]
I removed it out of the line. you'll have to `npm install autorest@beta` again in a few minutes

Oddly enough, env does the right thing from the shell, but not here.

**Comment by kevinoid** [comment]
> I removed it out of the line. you'll have to npm install autorest@beta again in a few minutes

Thanks @fearthecowboy!  Will do.

> Oddly enough, env does the right thing from the shell, but not here.

Probably because argument splitting does not occur on the shebang.  If you'd like help working through the behavior differences, let me know.

**Comment by fearthecowboy** [comment]
We're boned. 

I don't think there is a cross-platform way that this can be solved without changing `cmd-shim`  in the `npm` repo.

**Comment by kevinoid** [comment]
Would it be possible to use [`v8.setFlagsFromString`](https://nodejs.org/api/v8.html#v8_v8_setflagsfromstring_flags)? (e.g. `v8.setFlagsFromString('--max_old_space_size=16384');`)

**Comment by fearthecowboy** [comment]
I was not aware of that. 

![image](https://morbotron.com/gif/S03E14/99181/103569.gif?b64lines=V293ISBOZWF0ISBPaCEKCkl0J3MgYSB0cml1bXBoIG9mIGZyZWUgCnNwaXJpdGVkIFY4IGVuZ2luZWVyaW5nLg==)

**Comment by kevinoid** [comment]
Haha!  Yes indeed.

I hope it works reasonably well.  I haven't used `v8.setFlagsFromString` much, and the warning in the documentation is pretty dire.  But, if `--max_old_space_size` is supported, it seems perfect.

**Comment by fearthecowboy** [comment]
Nope. Didn't work.

The max heap space doesn't change.


![image](https://morbotron.com/video/S06E01/BIqEa2wNLtC2g5RUPB71kKK9ejE=.gif)

**Comment by kevinoid** [comment]
Yep, we're boned.  I should have checked that.

I haven't been able to find a portable workaround that doesn't use some sort of wrapper/launcher script yet, but I'll keep thinking.  The two workarounds I have come up with so far are pretty gross:

1.  If `--max_old_space_size` was not passed, re-launch using `child_process.spawnSync` then exit with its exit code.  Similar to [`exec(3)`](https://manpages.debian.org/stretch/manpages-dev/exec.3.en.html), except that the parent process remains until exit (and some additional challenges checking/preserving V8 flags).
2.  Instead of setting `bin` in `package.json` and relying on `npm` to generate a wrapper, use a `postinstall` script to install an appropriate wrapper for the platform which includes `--max_old_space_size`.  It would require some subtlety finding the bin dir for global installations, but otherwise I think it would be straightforward.

**Comment by fearthecowboy** [comment]
I fixed that a while back. It now spawns another instance if it needs to add the switch.

**Comment by svett** [comment]
This issue is still applicable. I just installed autorest and it does not work.

**Comment by fearthecowboy** [comment]
I just installed it and it works fine:

![image](https://user-images.githubusercontent.com/133736/75383977-2f48ef80-5892-11ea-9392-4acb3232e96a.png)

What precisely did you do?

**Comment by daviwil** [comment]
Make sure you're using the right AutoRest version.  The `autorest` command no longer uses that shebang and configures the heap size using v8 APIs:

https://github.com/Azure/autorest/blob/master/autorest/entrypoints/app.js#L1

Try installing the latest build:

```
npm install -g https://github.com/Azure/autorest/releases/download/autorest-3.0.6194/autorest-3.0.6194.tgz
```

I'm running this on the Linux distribution Guix with Node 10.16.0 and it works fine.
