### ISSUE TITLE
[openapi-to-typespec] Missing `@typespec/versioning` import 

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/autorest#4931]
When converting a swagger to typespec, the `@versioned` decorator is correctly added, but the spec is missing the import and using statements. We need to add the following in the main.tsp ouput:

```
import "@typespec/versioning";

using TypeSpec.Versioning;
```

Showed up when converting the following spec: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/appconfiguration/data-plane/readme.md

**Comment by catalinaperalta** [comment]
Another issue with the versioning support, the enum needs to specify the Azure Core version is depends on. 

Current output:
```
@doc("The available API versions.")
enum Versions {
  v2023_11_01: "2023-11-01",
}
```


Expected output:
```
@doc("The available API versions.")
enum Versions {
  @useDependency(Azure.Core.Versions.v1_0_Preview_2)
  v2023_11_01: "2023-11-01",
}
```

**Comment by pshao25** [comment]
Could you check with the latest version? I believe both of your problem has been fixed now.

If not, could send a valid link of spec? The spec you provided fails in the M4 stage with error message:
```
Error: Couldn't determine the Pageable resource for the operation: GetKeys
```

**Comment by catalinaperalta** [comment]
Just tried with this readme: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/keyvault/data-plane/readme.md and looks like the import is still missing for data-plane spec conversion.
